const mongoose = require('mongoose');

const Schema = mongoose.Schema

// id is autogenerated by default in mongoose;

const duckieSchema = new Schema({
    name: {
        type: String, 
        default: "Duckie", 
        required: true
    },
    affection: {
        type: Number,
        default: 0
    },
    hunger: {
        type: Number,
        default: 0
    },
    study: {
        type: Number,
        default: 0
    },
    play: {
        type: Number,
        default: 0
    },
    dead: {
        type: Boolean, 
        default: false
    }
}, {timestamps: true})


module.exports = mongoose.model('Duckie', duckieSchema)